### ISSUE TITLE
Bug when loading the model

### ISSUE THREAD

**Issue by jsalbert** [titu1994/MobileNetworks#6]
Hi @titu1994,

I have the following script, after modifying your example predict.py to save and load the model

```
from __future__ import print_function
from __future__ import absolute_import

from keras.preprocessing import image
from keras.models import load_model
from mobilenets import MobileNet, preprocess_input, decode_predictions, relu6, DepthwiseConv2D

import numpy as np

if __name__ == '__main__':
    size = 224
    alpha = 1.0

    model = MobileNet(alpha=alpha, weights='imagenet')

    model.save('m.h5')

    model = load_model('m.h5', custom_objects={
                       'relu6': relu6,
                       'DepthwiseConv2D': DepthwiseConv2D})

    img_path = 'images/cheetah.jpg'
    img = image.load_img(img_path, target_size=(size, size))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)

    x = preprocess_input(x)

    preds = model.predict(x)

    print('Predicted:', decode_predictions(preds))
```

When loading the model I got the following error:

Traceback (most recent call last):
  File "/home/snormore/skinNet/mobileNet/MobileNetworks/predict_imagenet.py", line 20, in <module>
    'DepthwiseConv2D': DepthwiseConv2D})
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/models.py", line 233, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/models.py", line 307, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/engine/topology.py", line 2450, in from_config
    process_layer(layer_data)
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/engine/topology.py", line 2419, in process_layer
    custom_objects=custom_objects)
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/snormore/keras_env/lib/python2.7/site-packages/keras/engine/topology.py", line 1242, in from_config
    return cls(**config)
  File "/home/snormore/skinNet/mobileNet/MobileNetworks/mobilenets.py", line 186, in __init__
    self._strides = (1,) + strides + (1,)

Am I doing something wrong?
Thanks! Nice Repo :)

**Comment by titu1994** [comment]
While you are not doing anything wrong, seems to be a bug in how the internal strides is calculated. 

Btw, this MobileNets has been implemented in Keras 2.0.6. You can just upgrade your Keras, and use from keras.applications.mobilenet import MobileNet
